name: Buildroot reusable workflow
on:
  workflow_call:
    inputs:
      br_variant:
        required: true
        type: string
      br_tarball_name:
        required: true
        type: string
      br_tarball_target:
        required: true
        type: string

env:
  BR2_CCACHE: y
  BR2_CCACHE_DIR: ${{ github.workspace }}/.ccache

jobs:
  build_buildroot:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Restore br2dl
      id: cache-br2dl-restore
      uses: actions/cache/restore@v4
      with:
        path: buildroot/dl
        key: br2dl-${{ inputs.br_variant }}

    - name: Restore ccache
      id: cache-ccache-restore
      uses: actions/cache/restore@v4
      with:
        path: .ccache
        key: ccache-${{ inputs.br_variant }}

    - name: Setup env
      run: make installpkgs

    - name: Download
      run: make buildroot-${{ inputs.br_variant }}-source

    - name: Save br2dl
      id: cache-br2dl-save
      uses: actions/cache/save@v4
      with:
        path: buildroot/dl
        key: ${{ steps.cache-br2dl-restore.outputs.cache-primary-key }}-${{ github.run_id }}

    - name: Build
      run: make ${{ inputs.br_tarball_target }}

    - name: Save ccache
      id: cache-ccache-save
      uses: actions/cache/save@v4
      with:
        path: .ccache
        key: ${{ steps.cache-ccache-restore.outputs.cache-primary-key }}-${{ github.run_id }}

    - name: Stash
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.br_tarball_name }}
        path: ${{ inputs.br_tarball_target }}
