name: Clean up reusable workflow
on:
  workflow_call:
    inputs:
      br_tarball_name:
        required: true
        type: string
      qemu_tarball_name:
        required: true
        type: string

jobs:
  cleanup:
    runs-on: ubuntu-latest
      steps:
      - name: Cleanup buildroot tarball
        if: always()
        uses: actions/github-script@v7
        with:
            script: |
            github.rest.actions.deleteArtifact({
                owner: context.repo.owner,
                repo: context.repo.repo,
                artifact_id: ${{ inputs.br_tarball_name }}
            })

      - name: Cleanup qemu tarball
        if: always()
        uses: actions/github-script@v7
        with:
            script: |
            github.rest.actions.deleteArtifact({
                owner: context.repo.owner,
                repo: context.repo.repo,
                artifact_id: ${{ inputs.qemu_tarball_name }}
            })
