name: Clean up reusable workflow
on:
  workflow_call:
    inputs:
      toolchain_tarball_name:
        required: true
        type: string
      br_tarball_name:
        required: true
        type: string
      linux_tarball_name:
        required: true
        type: string
      qemu_tarball_name:
        required: true
        type: string

jobs:
  cleanup:
    runs-on: ubuntu-latest
    - uses: geekyeggo/delete-artifact@v5
      with:
          name: |
              ${{ inputs.toolchain_tarball_name }}
              ${{ inputs.br_tarball_name }}
              ${{ inputs.linux_tarball_name }}
              ${{ inputs.qemu_tarball_name }}
