name: Build all things
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: make installpkgs
      - run: make buildroot/output/images/rootfs.squashfs
      - run: make u-boot/build_virt/u-boot.elf.fudged
      - run: make u-boot/build_mc68ez328/u-boot.bin
      - run: make bootfiles/vmlinux.virt
      - run: make bootfiles/vmlinux.mc68ez328
      - run: make qemu/build/qemu-system-m68k
