name: Build all things
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: apt-get install git libglib2.0-dev libfdt-dev libpixman-1-dev zlib1g-dev ninja-build
      - run: make buildroot/output/images/rootfs.squashfs
      - run: make u-boot/u-boot.elf.fudged
      - run: make bootfiles/vmlinux
      - run: make qemu/build/qemu-system-m68k
