name: Build for LC475
on: [push]
jobs:
  build_buildroot:
    uses: ./.github/workflows/buildroot.yaml
    with:
      br_tarball_target: build/buildroot_040.tar.gz

  build_linux:
    needs: build_buildroot
    uses: ./.github/workflows/linux.yaml
    with:
      br_tarball_target: build/buildroot_040.tar.gz
      linux_make_target: linux-mac-build

  build_qemu:
    uses: ./.github/workflows/qemu.yaml
    with:
      br_tarball_target: build/buildroot_040.tar.gz

  test:
    runs-on: ubuntu-latest
    needs: [build_buildroot, build_linux, build_qemu]
    steps:
    - name: Boot test
      run: timeout 120s make run-qemu-virt || true
