name: Build for LC475
on: [push]
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

  build_buildroot:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
    - name: Restore br2dl
      id: cache-br2dl-restore
      uses: actions/cache/restore@v4
      with:
        path: buildroot/dl
        key: ${{ runner.os }}-br2dl

    - name: Setup env
      run: make installpkgs

    - name: Download
      run: make buildroot-040-source

    - name: Save br2dl
      id: cache-primes-save
      uses: actions/cache/save@v4
      with:
        path: buildroot/dl
        key: ${{ steps.cache-br2dl-restore.outputs.cache-primary-key }}

    - name: Buildroot
      run: make buildroot-040-build

  build_linux:
    runs-on: ubuntu-latest
    needs: build_buildroot
    steps:
    - name: Linux
      run: make linux-mac-build

  build_qemu:
    runs-on: ubuntu-latest
    needs: build_buildroot
    steps:
    - name: QEMU
      run: make build/qemu.build.stamp

  test:
    runs-on: ubuntu-latest
    needs:
      build_buildroot
      build_linux
      build_qemu
    steps:
    - name: Boot test
      run: timeout 120s make run-qemu-virt || true
