name: Build for LC475
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: make installpkgs
      - run: make buildroot-040-build
      - run: find build/
