name: Build for LC475
on: [push]
jobs:
  build_buildroot:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Restore br2dl
      id: cache-br2dl-restore
      uses: actions/cache/restore@v4
      with:
        path: buildroot/dl
        key: ${{ runner.os }}-br2dl

    - name: Setup env
      run: make installpkgs

    - name: Download
      run: make buildroot-040-source

    - name: Save br2dl
      id: cache-primes-save
      uses: actions/cache/save@v4
      with:
        path: buildroot/dl
        key: ${{ steps.cache-br2dl-restore.outputs.cache-primary-key }}

    - name: Build
      run: make build/buildroot_040.tar.gz

    - name: Stash
      uses: actions/upload-artifact@v4
      with:
        name: buildroot_tar_gz
        path: build/buildroot_040.tar.gz

  build_linux:
    runs-on: ubuntu-latest
    needs: build_buildroot
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Setup env
      run: make installpkgs

    - name: Restore environment
      uses: actions/download-artifact@v4
      with:
        name: buildroot_tar_gz
        path: build/buildroot_040.tar.gz

    - name: Restore buildroot
      run: tar xvzf build/buildroot_040.tar.gz

    - name: Build
      run: make linux-mac-build

  build_qemu:
    runs-on: ubuntu-latest
    needs: build_buildroot
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Build
      run: make build/qemu.build.stamp

  test:
    runs-on: ubuntu-latest
    needs: [build_buildroot, build_linux, build_qemu]
    steps:
    - name: Boot test
      run: timeout 120s make run-qemu-virt || true
