name: Build for LC475
on: [push]
jobs:
  build_buildroot:
    steps:
    - uses: ./.github/workflows/buildroot.yml
      with:
        br_tarball_target: build/buildroot_040.tar.gz

  build_linux:
    runs-on: ubuntu-latest
    needs: build_buildroot
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Setup env
      run: make installpkgs

    - name: Restore environment
      uses: actions/download-artifact@v4
      with:
        name: buildroot_tar_gz
        path: build/buildroot_040.tar.gz

    - name: Restore buildroot
      run: tar xvzf build/buildroot_040.tar.gz

    - name: Build
      run: make linux-mac-build

  build_qemu:
    runs-on: ubuntu-latest
    needs: build_buildroot
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Build
      run: make build/qemu.build.stamp

  test:
    runs-on: ubuntu-latest
    needs: [build_buildroot, build_linux, build_qemu]
    steps:
    - name: Boot test
      run: timeout 120s make run-qemu-virt || true
