name: Build for LC475
on: [push]
jobs:
  toolchain:
    uses: ./.github/workflows/buildroot.yaml
    with:
      br_tarball_name: br_toolchain_tarball
      br_tarball_target: build/buildroot_040_toolchain.tar.gz

  linux:
    needs: toolchain
    uses: ./.github/workflows/linux.yaml
    with:
      br_tarball_name: br_toolchain_tarball
      br_tarball_target: build/buildroot_040_toolchain.tar.gz
      linux_make_target: linux-mac-build

  buildroot:
    needs: toolchain
    uses: ./.github/workflows/buildroot.yaml
    with:
      br_tarball_name: br_tarball
      br_tarball_target: build/buildroot_040.tar.gz

  qemu:
    uses: ./.github/workflows/qemu.yaml
    with:
      br_tarball_target: build/buildroot_040.tar.gz

  test:
    runs-on: ubuntu-latest
    needs: [buildroot, linux, qemu]
    steps:
    - name: Boot test
      run: timeout 120s make run-qemu-virt || true
