name: Build for mc68ez328
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: make installpkgs
      - run: make build/buildroot_000.build.stamp
      - run: make build/u-boot.mc68ez328.build.stamp
      - run: make build/linux.mc68ez328.build.stamp
      - run: make build/qemu.build.stamp
      - run: find build/
      - run: timeout 30s make run-qemu-mc68ec328 || true
