name: Build for mvme147
on: [push]
jobs:
  toolchain:
    uses: ./.github/workflows/buildroot.yaml
    with:
      br_variant: "030"
      br_tarball_name: br_toolchain_tarball
      br_tarball_target: build/buildroot_030_toolchain.tar.gz

  uboot:
    needs: toolchain
    uses: ./.github/workflows/uboot.yaml
    with:
      br_tarball_name: br_toolchain_tarball
      br_tarball_target: build/buildroot_030_toolchain.tar.gz
      uboot_tarball_name: uboot_mvme147_tarball
      uboot_tarball_target: build/u-boot.mvme147.tar.gz

  linux:
    needs: toolchain
    uses: ./.github/workflows/linux.yaml
    with:
      br_tarball_name: br_toolchain_tarball
      br_tarball_target: build/buildroot_030_toolchain.tar.gz
      linux_tarball_name: linux_mvme147_tarball
      linux_tarball_target: build/linux.mvme147.tar.gz

  buildroot:
    needs: toolchain
    uses: ./.github/workflows/buildroot.yaml
    with:
      br_variant: "030"
      br_tarball_name: br_tarball
      br_tarball_target: build/buildroot_030.tar.gz

  qemu:
    uses: ./.github/workflows/qemu.yaml
    with:
      tarball_name: qemu_tarball
      tarball_target: build/qemu.tar.gz

  cleanup:
    needs: [ qemu, buildroot, linux ]
    uses: ./.github/workflows/cleanup.yaml
    with:
      toolchain_tarball_name: br_toolchain_tarball
      br_tarball_name: br_tarball
      linux_tarball_name: linux_mvme147_tarball
      qemu_tarball_name: qemu_tarball
