name: QEMU reusable workflow
on:
  workflow_call:
    inputs:
      tarball_name:
        required: true
        type: string
      tarball_target:
        required: true
        type: string
jobs:
  build_qemu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Setup env
      run: make installpkgs
        
    - name: Build
      run: make ${{ inputs.tarball_target }}

    - name: Stash
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.tarball_name }}
        path: ${{ inputs.tarball_target }}
