name: QEMU reusable workflow
on:
  workflow_call:
    inputs:
      br_tarball_target:
        required: false
        type: string

jobs:
  build_qemu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Setup env
      run: make installpkgs
        
    - name: Build
      run: make build/qemu.tar.gz

    - name: Stash
      uses: actions/upload-artifact@v4
      with:
        name: qemu_tar_gz
        path: build/qemu.tar.gz
