name: Build for virt
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: make installpkgs
      - run: make build/buildroot_000.build.stamp
      - run: make build/u-boot.virt.build.stamp
      - run: make build/linux.virt.build.stamp
      - run: make build/qemu.build.stamp
      - run: timeout 30s make run-qemu-virt || true
