name: Build for virt-nommu
on: [push]
jobs:
  toolchain:
    uses: ./.github/workflows/buildroot.yaml
    with:
      br_variant: "000"
      br_tarball_name: br_toolchain_tarball
      br_tarball_target: build/buildroot_000_toolchain.tar.gz

  uboot:
    needs: toolchain
    uses: ./.github/workflows/uboot.yaml
    with:
      br_tarball_name: br_toolchain_tarball
      br_tarball_target: build/buildroot_000_toolchain.tar.gz
      uboot_tarball_name: uboot_virt_tarball
      uboot_tarball_target: build/u-boot.virt.tar.gz

  linux:
    needs: toolchain
    uses: ./.github/workflows/linux.yaml
    with:
      br_tarball_name: br_toolchain_tarball
      br_tarball_target: build/buildroot_000_toolchain.tar.gz
      linux_tarball_name: linux_virt_tarball
      linux_tarball_target: build/linux.virt.tar.gz

  buildroot:
    needs: toolchain
    uses: ./.github/workflows/buildroot.yaml
    with:
      br_variant: "000"
      br_tarball_name: br_tarball
      br_tarball_target: build/buildroot_000.tar.gz

  qemu:
    uses: ./.github/workflows/qemu.yaml
    with:
      tarball_name: qemu_tarball
      tarball_target: build/qemu.tar.gz

  test:
    needs: [buildroot, uboot, linux, qemu]
    uses: ./.github/workflows/test.yaml
    with:
      br_tarball_name: br_tarball
      br_tarball_target: build/buildroot_000.tar.gz
      uboot_tarball_name: uboot_virt_tarball
      uboot_tarball_target: build/u-boot.virt.tar.gz
      linux_tarball_name: linux_virt_tarball
      linux_tarball_target: build/linux.virt.tar.gz
      qemu_tarball_name: qemu_tarball
      qemu_tarball_target: build/qemu.tar.gz
      run_target: run-qemu-virt

  cleanup:
    needs: test
    uses: ./.github/workflows/cleanup.yaml
    with:
      toolchain_tarball_name: br_toolchain_tarball
      br_tarball_name: br_tarball
      linux_tarball_name: linux_virt_tarball
      qemu_tarball_name: qemu_tarball
